const strategies = [
  "(Organic) machinery",
  "A line has two sides",
  "A very small object         Its center",
  "Abandon desire",
  "Abandon normal instructions",
  "Abandon normal instruments",
  "Accept advice",
  "Accretion",
  "Adding on",
  "Allow an easement (an easement is the abandonment of a stricture)",
  "Always first steps",
  "Always give yourself credit for having more than personality",
  "Are there sections?  Consider transitions",
  "Ask people to work against their better judgement",
  "Ask your body",
  "Assemble some of the elements in a group and treat the group",
  "Balance the consistency principle with the inconsistency principle",
  "Be dirty",
  "Be extravagant",
  "Be less critical",
  "Breathe more deeply",
  "Bridges --build --burn",
  "Cascades",
  "Change ambiguities to specifics",
  "Change instrument roles",
  "Change nothing and continue with immaculate consistency",
  "Change specifics to ambiguities",
  "Children --speaking --singing",
  "Cluster analysis",
  "Consider different fading systems",
  "Consider transitions",
  "Consult other sources --promising --unpromising",
  "Convert a melodic element into a rhythmic element",
  "Courage!",
  "Cut a vital connection",
  "Decorate, decorate",
  "Define an area as `safe' and use it as an anchor",
  "Destroy -nothing -the most important thing",
  "Discard an axiom",
  "Disciplined self-indulgence",
  "Disconnect from desire",
  "Discover the recipes you are using and abandon them",
  "Display your talent",
  "Distort time",
  "Do nothing for as long as possible",
  "Do something boring",
  "Do the last thing first",
  "Do the washing up",
  "Do the words need changing?",
  "Do we need holes?",
  "Don't avoid what is easy",
  "Don't be frightened of cliches",
  "Don't break the silence",
  "Don't stress one thing more than another",
  "Dont be afraid of things because they're easy to do",
  "Dont be frightened to display your talents",
  "Emphasize differences",
  "Emphasize repetitions",
  "Emphasize the flaws",
  "Faced with a choice, do both (given by Dieter Rot)",
  "Feed the recording back out of the medium",
  "Fill every beat with something",
  "Find a safe part and use it as an anchor",
  "Get your neck massaged",
  "Ghost echoes",
  "Give the game away",
  "Give way to your worst impulse",
  "Go outside. Shut the door.",
  "Go slowly all the way round the outside",
  "Go to an extreme, come part way back",
  "Honor thy mistake as a hidden intention",
  "How would someone else do it?",
  "How would you have done it?",
  "Humanize something free of error",
  "Idiot glee (?)",
  "Imagine the piece as a set of disconnected events",
  "In total darkness, or in a very large room, very quietly",
  "Infinitesimal gradations",
  "Intentions --nobility of --humility of --credibility of",
  "Into the impossible",
  "Is it finished?",
  "Is something missing?",
  "Is the information correct?",
  "Is the style right?",
  "Is there something missing",
  "It is quite possible (after all)",
  "It is simply a matter of work",
  "Just carry on",
  "Left channel, right channel, center channel",
  "Listen to the quiet voice",
  "Look at the order in which you do things",
  "Look closely at the most embarrassing details & amplify them",
  "Lost in useless territory",
  "Lowest common denominator",
  "Magnify the most difficult details",
  "Make a blank valuable by putting it in an exquisite frame",
  "Make a sudden, destructive unpredictable action; incorporate",
  "Make an exhaustive list of everything you might do & do the last thing on the list",
  "Make it more sensual",
  "Make what's perfect more human",
  "Mechanicalize something idiosyncratic",
  "Move towards the unimportant",
  "Mute and continue",
  "Not building a wall but making a brick",
  "Once the search has begun, something will be found",
  "Only a part, not the whole",
  "Only one element of each kind",
  "Overtly resist change",
  "Pae White's non-blank graphic metacard",
  "Put in earplugs",
  "Question the heroic",
  "Reevaluation (a warm feeling)",
  "Remember those quiet evenings",
  "Remove a restriction",
  "Remove ambiguities and convert to specifics",
  "Remove specifics and convert to ambiguities",
  "Repetition is a form of change",
  "Retrace your steps",
  "Reverse",
  "Short circuit (example; a man eating peas with the idea that they will improve  his virility shovels them straight into his lap)",
  "Simple subtraction",
  "Simply a matter of work",
  "Slow preparation, fast execution",
  "Spectrum analysis",
  "State the problem as clearly as possible",
  "Take a break",
  "Take away the elements in order of apparent non-importance",
  "Take away the important parts",
  "Tape your mouth (given by Ritva Saarikko)",
  "The inconsistency principle",
  "The most important thing is the thing most easily forgotten",
  "The tape is now the music",
  "Think --inside the work --outside the work",
  "Think of the radio",
  "Tidy up",
  "Towards the insignificant",
  "Trust in the you of now",
  "Try faking it (from Stewart Brand)",
  "Turn it upside down",
  "Twist the spine",
  "Use 'unqualified' people",
  "Use an old idea",
  "Use an unacceptable color",
  "Use cliches",
  "Use fewer notes",
  "Use filters",
  "Use something nearby as a model",
  "Use your own ideas",
  "Voice your suspicions",
  "Water",
  "What are the sections sections of?    Imagine a caterpillar moving",
  "What are you really thinking about just now?",
  "What context would look right?",
  "What is the reality of the situation?",
  "What is the simplest solution?",
  "What mistakes did you make last time?",
  "What to increase? What to reduce? What to maintain?",
  "What would your closest friend do?",
  "What wouldn't you do?",
  "When is it for?",
  "Where is the edge?",
  "Which parts can be grouped?",
  "Work at a different speed",
  "Would anyone want it?",
  "You are an engineer",
  "You can only make one dot at a time",
  "You don't have to be ashamed of using your own ideas",
  "Faced with a choice, do both things.",
  "Make an exhaustive list of everything you might do next.",
  "Try to make the problem worse to understand how you might make it better.",
  "Do nothing for as long as possible.",
  "Break a big thing up into smaller pieces.",
  "Remember that models don't necessarily correspond with reality.",
  "Generate alternative solutions and pick the best.",
  "Can you make this program do one thing instead of two?",
  "Is this abstraction delivering enough benefit?",
  "Are you solving the right problem?",
  "Are you solving the problem you have or the problem you'd like to have?",
  "Can you automate this?",
  "If it doesn't work, it doesn't matter how fast it doesn't work.",
  "Are you clear about what you are trying to build?",
  "Do you even know what you're talking about?",
  "Could the documentation be wrong?",
  "Does the code actually do what the comments say it should?",
  "Is this premature optimization?",
  "Write a plan then throw it away.",
  "Is this what the customer wants or is it what he needs?",
  "Can you build something to help you understand the problem?",
  "Before software can be reusable it first has to be usable.",
  "Does this need a program or could I use another tool?",
  "First, solve the problem. Then, write the code.",
  "Simplicity is prerequisite for reliability.",
  "Easy things hould be easy; hard things should be possible.",
  "The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.",
  "Deleted code is debugged code.",
  "Are you getting confused by the complexities of your own making?",
  "Don't worry about what anybody else is doing.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "The key to performance is elegance, not battalions of special cases.",
  "Watch out for off-by-one bugs where loops are used.",
  "If there are two or more ways to do something, and one of those ways can result in a catastrophe, then someone will do it.",
  "Make some time and space to learn some new skills.",
  "If you have four groups working on a compiler, you'll get a four-pass compiler.",
  "Resist the temptation to fix it by hand. Make sure the fix is permanent.",
  "Can you use brute force for now and find a fancy algorithm later?",
  "Is it broken by design?",
  "A twin-engine aeroplane has twice as many engine problems as a single engine aeroplane.",
  "Imagine a day in the life of a user of your software.",
  "Go to the library. Sit quietly and think.",
  "Can you find an analogy or metaphor to explore this problem?",
  "KISS: Keep It Short and Simple. Keep It Simple Stupid!",
  "When did it last work? what has changed?",
  "What's the worse thing that could happen next?",
  "What would be the implications of ignoring this problem and doing nothing about it for the time being?",
  "The simplest explanation is most likely the correct one.",
  "What would a layman or somebody with less experience do?",
  "Shouting and swearing won't help. Clear, rational thinking almost certainly will.",
  "Be quiet! Stop talking and think!",
  "Can you get more information from the customer? Real data? A crash dump? Configuration settings? Virtual machine image?",
  "Is it time to upgrade your computer?",
  "Is there a test or simulation that you could run overnight to give you more information tomorrow?",
  "Is this code really necessary?",
  "Can I simplify the problem somehow?",
  "Only change one thing at a time. Try to predict what will happen with each change.",
  "Find a code sample.",
  "Stop guessing and look at the facts.",
  "Are you fooling yourself?",
  "Could you build a textualizer utility to help manage your data files?",
  "Write some more unit tests.",
  "Have you switched it off and back on again?",
  "Keep a written log of every little thing you change and any results.",
  "Is there a better algorithm? Consult the computer science literature.",
  "Idly thumb through The Gang of Four Design Patterns book.",
  "Idly thumb through The Art of Computer Science by Donald Knuth.",
  "Designing the right data structure is often more important than designing the right code.",
  "How could you go about formally proving this code to be correct?",
  "Is this code part of a design pattern? What's its name?",
  "Get away from your desk. Take a journey on public transport: a train, bus or plane.",
  "Strum your guitar.",
  "Be alone for a while. Make some time and space to really think.",
  "If you are thinking and not writing you only think you are thinking.",
  "Collect together all the information, pictures, scribbles and diagrams. Make a scrapbook or pin them to the wall.",
  "Tidy up your work area.",
  "Are you looking in the right place?",
  "Is this a symptom or a root cause?",
  "Take a break; Read a poem.",
  "Take a break; Look at a painting.",
  "Try recreating this program section from scratch.",
  "What would this code look like in another programming language?",
  "Try to write a small, reproducible code sample with just the salient parts and all other complexity removed.",
  "Is this a numerical problem? Think about rounding, division by zero, overflow and floating point errors.",
  "Are you using the correct configuration settings?",
  "Is this a versioning problem? Check the versions of your operating system, tools and libraries.",
  "Is there a video about this? Look on YouTube or Channel 9.",
  "Is there a standards approach to this?",
  "If you had time to refactor this code, what would you change?",
  "Can you pair program it?",
  "How did they do it without computers?",
  "Don't assume that the bug was caused by somebody else.",
  "Is there somebody you could call upon for assistance?",
  "Build expertise in your project's domain. Talk to expert users. Read industry papers, academic reports, brochures etc.",
  "Buy a book on the subject.",
  "Take a smoke break, even if you don't actually smoke. (Smokers always know what's going on).",
  "Walk a lap around the car park.",
  "Make a cup of tea or coffee.",
  "Don't invent another data format.",
  "Go outside and get some fresh air.",
  "Take a break; go for a run or do some cardiovascular exercise.",
  "Stand in front of a big blank whiteboard with a pen. Start writing.",
  "Draw a picture of the problem with coloured pens.",
  "Try to reproduce the problem on a different computer or different hardware.",
  "What's the simplest thing that could possibly work?",
  "Explain the problem to a co-worker.",
  "Think about what is going on at the lowest layers. What is hitting RAM? What is being sent on the wire?",
  "Try using a different web browser.",
  "Try it on a different network. 3G, Starbucks WIFI or home broadband.",
  "Work in a coffee shop or cafe for a while.",
  "Work from home for a day.",
  "Lie on the sofa with your laptop.",
  "Read the error message slowly, carefully and deliberately. What does it actually say?",
  "Go and sit next to a user of your software.",
  "Can you add code that will provide more information about the problem?",
  "Comment out all the exception and error handlers and try again.",
  "Look hard at any loops. Under what circumstances can they terminate?",
  "Check the types of all the variables in the problematic code.",
  "Rollback or undo the last change.",
  "Does turning OFF any compiler optimizations or debugging tools change the problem?",
  "Write down a clear statement of the problem on paper.",
  "What would Donald Knuth do?",
  "What would Steve Jobs have done?",
  "What would Paul Graham do?",
  "What is the worst thing you could do next?",
  "Can you find some similar code in an open source project and study it?",
  "Go and talk to somebody who isn't a programmer.",
  "Switch off your monitor and sit at your desk quietly for a while.",
  "Shut your eyes for five minutes.",
  "Take a break. Go and get something to eat.",
  "Ignore the problem and work on something else for a while.",
  "Ask a question on Stack Overflow.",
  "Ponder the Telergraph Crossword.",
  "Post the problem on a forum or news group.",
  "Google it.",
  "Can you reuse an old idea or code from an earlier project?",
  "Go home and sleep on it. Things will look different tomorrow.",
  "Can you do this job without writing any more code?",
  "Try to imagine what the world would look like if you had already solved the problem.",
  "Are you using the right tools for the job?",
  "Do your names and abstractions correspond with the real world? Is your code model driven?",
  "Just because other people think it's a bug doesn't mean it's really a bug.",
  "Perform the calculation or task manually with a calculator, pencil and paper.",
  "Consider the possibility of side effects.",
  "Is there an existing library or component that you could use?",
  "Have a long soak in a hot bath.",
  "Are there any log files that might give you more information?",
  "Are there any compiler flags or runtime switches that you could configure to give you more information?",
  "If you are the only person fixing a problem, then people will just have to wait until you're done.",
  "What can you do to contain a problem so that things can't get any worse?",
  "Keep calm and breathe.",
  "Every problem has a perfectly reasonable explanation.",
  "Can you use a tool to watch what's happening? A debugger, protocol analyzer or trace listener for example.",
  "Be wary of Not Invented Here syndrome.",
  "Can you adapt something that you already have?",
  "Read the documentation properly. Read it again.",
  "Can you build a simulator to help reproduce the problem conditions?",
  "Imagine you had unlimitted time, budget, memory and compute power. What would you do?",
  "Don't trust a bug report until you've seen the problem with your own eyes."
]

module.exports = strategies
